### PR TITLE
WIP: Python 3 support

### PR DESCRIPTION
**Pull request by cgranade**
This PR collects the work started by @scasagrande on fixing problems that keep QInfer tied to Python 2.7, and brings it inline with QuTiP, InstrumentKit and other modern libraries used in quantum info.

### CODE REVIEW

**Comment by scasagrande** [comment]
So I've added a pylint checker to travis to help avoid problems with future commits.

I think we're good to go here.

**Comment by cgranade** [comment]
Sounds good. Running pylint's py3k mode locally didn't find any problems either, so I agree, it seems like it's good to merge in. That way, we'll get your pylint configuration on everything else, too. Thank you for all the help!

**Comment by scasagrande** [comment]
No problem :)

I didn't include a `.pylintrc` file because I'm just using the default setting there with the `--py3k` flag. One thing that I did notice about it is that you have to run with a `python2.7` env to actually see the problems. Running it from `python3` won't error because it won't find any invalid py3 syntax for your py3 env.

**Comment by cgranade** [comment]
Right, I ran into that as well. May even be worth guarding the pylint call with a check of the Travis build matrix, then. I'll make a new PR for that, since I need to do some other CI configuration stuff anyway.

**Comment by scasagrande** [comment]
I'd just leave it running in the other versions. I'm not sure if it also checks for things incompatible between py3 versions. For example, it might get angry when running on `python3.3` if it comes across a `yield from` statement.

If not, it just passes anyways.

**Comment by cgranade** [comment]
Ah, good point. I'll leave it, then, as you suggest.

**Pull request merged**
