### PR TITLE
Added some generic distributions

### PR DESCRIPTION
**Pull request by ihincks**
Added beta, gamma, and beta-binomial Distributions. Should be useful as priors for models involving classical probabilities and/or binomial RVs.

I have not submitted a PR in a long while, and there seems to be some new stuff going on. Please let me know if I have not met the new standard. I also don't fully understand how read the docs works.

Also, I'm not sure what's going on with unit tests. I put some in src/tests/test_distributions.py, but there are also some test looking things in the parent folder, src/. The file test_distributions.py is also not imported anywhere, but test_models.py is, so wondering what the plan is.

### CODE REVIEW

**Comment by ihincks** [comment]
Also, sorry for the diff spam inserted by my text editor.

**Comment by cgranade** [comment]
Thanks for the PR, looks like a great addition! As for the docs, basically the new distributions should be added to ``doc/source/apiref/distributions.rst`` as ``.. autofunction::`` directives. This will pull in the docstrings for the various classes as reStructuredText. I'm happy to take care of that, as I'm in the middle of putting finishing touches on the docs anyway (branch ``feature-improved_docs``).

The unit testing is relatively new, and yeah, there's some duplication to it that I'd like to resolve. Part of it is that the module ``test_models.py`` was named that before unit tests were introduced, so that name is a terrible one. In particular, ``py.test`` automatically looks for modules with names matching ``*.tests.test_*``, so that ``test_distributions.py`` should not be explicitly imported. With moving everything into the root package using ``qinfer/__init__.py``, we should be able to move code out of ``test_models.py`` with a deprecation warning. That way, any module starting with ``test_*`` would properly be a run by ``py.test`` and not imported by anything else. Until then, though, I apologize for the confusion— your new tests seem to be found OK by ``py.test`` as called by Travis CI, so that all works.

The only comment that I had, I guess, was that it seems as though this PR duplicates ``MultivariateNormalDistribution``. If so, is that intentional? Anyway, thank you again for the PR!

(As for the whitespace changes in the diff, no worries, helps with PEP8 compliance to get rid of the extraneous whitespace anyway!)

**Comment by ihincks** [comment]
Thanks for explaining the status of unit tests.

The extra `MultivariateNormalDistribution` was just one too many ctrl+v's. Fixed.

**Comment by cgranade** [comment]
Thanks! I'll go on and merge this in, then, and get the new classes integrated into the API reference.

(The Travis CI build failure seems to be that an update to ``conda`` breaks 3.3 compatibility in the root env, so I'll deal with that separately. After a bit of investigation, it seems as though we'll need to install Python 3.3 in a different conda env to prevent depending on the ``conda`` package directly.)

**Pull request merged**
