### PR TITLE
Insert required numpy version.

### PR DESCRIPTION
**Pull request by ihincks**
Not sure what ``requirements.txt`` is used for, but unit testing is failing for me because of the ``dtype ``option in ``np.linspace``.

### CODE REVIEW

**Comment by scasagrande** [comment]
:ship:

**Comment by ihincks** [comment]
Are you making fun of my 7 character PR, Steven?

This PR was only partially a joke.

**Comment by cgranade** [comment]
NumPy 1.9 changed a whole bunch of internals, such that we really shouldn't be depending on anything earlier anyway. I think this is a good change, and should be merged in. The build failures seem to be related to the same BS where the root conda env can no longer run on 3.3 due to conda's dependency on rumel_yaml. We should fix that by doing everything in a new env instead of the root, but that shouldn't affect this PR.

**Comment by ihincks** [comment]
@scasagrande Ah, that makes more sense.

**Comment by cgranade** [comment]
On that note, I'll merge this in now. Thanks!

**Pull request merged**
