### PR TITLE
Fix Bayes Risk Evaluation to sum over the total posterior normalization

### PR DESCRIPTION
**Pull request by whitewhim2718**
@ihincks  and I noticed what we believe to be an error in the math that the Bayes risk function is currently evaluating. The issue we believe is that the  weighting of the variance should be by the total posterior likelihood weights, rather than the total likelihood weights. The two values are the same in the  case of uniform weights. Below is a picture of the calculation we believe supports this change. 

risk_derivation

### CODE REVIEW

**Comment by ihincks** [comment]
"The two values are the same in the case of uniform weights."

In particular, this implies a simple test where you do an update with no resample, ask for the risk of something, resample, and then ask for the risk again. They should be equal up to particle noise, but this issue alleges they would not be.

**Comment by cgranade** [comment]
I don't see where ``hypothetical_update`` is changed to accept a ``return_normalization`` kwarg? In any case, I think that the calculation looks correct. Thank you for catching this one!

**Comment by ihincks** [comment]
I think `hypothetical_update` already had this ability, although I don't know where else it is used.

**Comment by cgranade** [comment]
Ah, right, I forgot about that. I feel rather silly, then. In any case, this looks like a good fix; thank you again for that! The Travis failure is the same incompatability between the ``conda`` program itself and Py3.3, so I am happy to merge it in as-is.

**Comment by whitewhim2718** [comment]
@ihincks and I have another small fix. This fix is to `expected_information_gain`. Analysis is below 
new doc_1

**Comment by ihincks** [comment]
Note that the final formula in the above picture agrees exactly with the second last line of pseudo-code in Algorithm 5 of the paper "Robust Online Hamiltonian Learning", if you expand out the subtraction of entropies into sums.

**Comment by scasagrande** [comment]
Needs tests to cover the bug that was found

**Comment by cgranade** [comment]
I agree with this change as well, thanks for catching it, too.

**Pull request merged**
