### PR TITLE
Unit test fixes

### PR DESCRIPTION
**Pull request by MichalKononenko**
First PR to this library: Here we go

In issue #28, I mentioned about introducing Travis CI, coveralls, and better unit testing into python-qinfer. Here is an example of what I want to implement. Please comment, and I will polish this up for merging.

### CODE REVIEW

**Comment by cgranade** [comment]
I'm away on travel at the moment, so it will take me a bit to look over this, but this looks really useful. Thank you for the PR!

**Comment by MichalKononenko** [comment]
I've added a new commit, and I found the clustering algorithm is failing to cluster things with unweighted distributions. Do we still want to support non-weighted clustering in ``clustering.py``?

**Comment by cgranade** [comment]
Apologies again for the delay, and thank you for both your patience and your contribution! Looking over w/ @csferrie, I think this is a quite good PR, but I am concerned about the renaming of modules and functions to avoid clashes with ``nosetests`` naming conventions. In particular, even though ``perf_testing.py`` was probably not the best name for me to have chosen initially, it's what I did choose, and what is now heavily used by me and @ysanders (hopefully others as well). In particular, ``perf_testing`` was used in an arXiv posting from September, so I'm a bit leery of breaking the code in that paper. From that standpoint, it might make sense to keep the original names and decorate them so ``nostests`` doesn't see them, or to deprecate the original names more gradually such that running older code breaks in a way that's clear to users. There's a couple other minor things— some of the individual docstrings need some revision, and I don't know that I agree with all of the PEP8/pylint style fixes, but other than that, I again think this is a good PR. I am very happy for your contribution. Thank you!

**Comment by MichalKononenko** [comment]
I understand. unittest has some built-in regex to match test names, so we could likely blacklist that folder as a test. I'll look into that.

**Pull request closed without merging**
