### PR TITLE
Changed QuTiP to pull from PyPI.

### LINKED ISSUE #107: Travis CI DOCTEST=1 build broken
As encountered in the CI builds for #106, upstream changes in QuTiP have prevented doctest builds from running correctly. I think it makes sense to switch the doctest environment to install the released QuTiP version instead of the one from their Git master, now that the released version has everything we need for tomography support.

### PR DESCRIPTION
**Pull request by cgranade**
This PR should fix #107 and allow for proper testing of #106.

### CODE REVIEW

**Comment by ihincks** [comment]
Travis: `There was an error while loading data. ` ??

**Comment by cgranade** [comment]
I've been getting this on all Travis builds recently. I'm not sure what's
going on, but I'll investigate.

**Comment by cgranade** [comment]
The Travis CI builds seem to be broken only for this project, so I'll go on and send them a message and let you know what they say.

**Comment by cgranade** [comment]
I've [filed an issue](https://github.com/travis-ci/travis-ci/issues/7278) with Travis CI, we'll see if that gets addressed soon. Looks like it's an internal server error on their end, though, that's propagating outward through the JSON API in a way that's not handled especially well by the client-side web app.

**Comment by cgranade** [comment]
It seems as though our use of encrypted environment variables to support automatic PyPI deployment may have triggered an internal bug within Travis. In lieu of a permanent fix, I've worked around this for now with 7fcf6b2, which moves encrypted environment variables from the repository settings to ``.travis.yml``. This workaround seems to be working for now, hopefully?

**Comment by cgranade** [comment]
Now that the Travis builds are working, I can diagnose the underlying problem: it seems as though the very old version of GCC used by default on Travis is not compatible with recent QuTiP releases, such that we need to bump up to at least 4.8. There's some instructions to be found [in other Travis CI issues](https://github.com/travis-ci/travis-ci/issues/5627), such that hopefully the latest build should work.

**Comment by cgranade** [comment]
Since all checks now pass, I'd like to get this PR merged in ASAP to help test other pending PRs. Marking it as ready for review.

**Pull request merged**
