### PR TITLE
Bump to version 1.0.

### PR DESCRIPTION
**Pull request by cgranade**
This is it, the 1.0 PR. If we agree and merge this in, then I will begin following the [release steps listed in the Wiki](https://github.com/QInfer/python-qinfer/wiki/Development-Guide) to formally release 1.0.

### CODE REVIEW

**Comment by whitewhim2718** [comment]
I cannot think of any additional features that should be in 1.0 off the top of my head. Once builds are passing I think it is ready to go, unless someone else disagrees. 

I want to thank you for all of your hard work Chris', and congratulate you on making it to 1.0. I think this software and type of analysis will be increasingly important to the field, and I look forward to seeing it develop. 

Once again thank you for the sleepless nights.

-Thomas

**Comment by cgranade** [comment]
With #98 and the current build failures, I think it might make sense to hold off just a little bit longer, but I wanted to have the PR in early to track the discussion on the release.

In any case, thank you very much for all of your kind contributions, testing, discussions and, well, everything. ♥

**Comment by ihincks** [comment]
I'll try to get #98 done quickly, shouldn't be too bad. I would bet money that I won't find any bugs in the non-obscure distributions, so it kind of feels like a waste of time. But this is offset with the satisfaction of increasing coverage.

**Comment by ihincks** [comment]
But yeah, 1.0 is definitely here.

**Comment by cgranade** [comment]
We did it, version 1.0 is here. Congratulations and my thanks to everyone, I think we've built something great here.

**Pull request merged**
