### PR TITLE
Contributions to feature-scipy-qhull

### PR DESCRIPTION
**Pull request by ihincks**
Added some documentation and tests. Extended modelparam_slice to the other region functions.

### CODE REVIEW

**Comment by ihincks** [comment]
The tests are failing, at the moment, because they require FiniteOutcomeTest. Would you mind merging master into your branch, @cgranade? There should be no conflicts.

**Comment by cgranade** [comment]
That should do it, will force a re-run of the tests now.

**Comment by cgranade** [comment]
This is fun, looks as though the conda-based CI builds are broken. I'll investigate today, sorry for the hassle.

**Comment by cgranade** [comment]
Following merging in #87, going to merge master back into the topic branch and see if that fixes the CI builds.

**Comment by cgranade** [comment]
I think it makes sense to merge this into the WIP PR #84 so as to pull in the new unit tests and CI fixes.

**Pull request merged**
