### PR TITLE
Added and documented resampler abc, fixes for CI builds.

### PR DESCRIPTION
**Pull request by cgranade**
Addresses #74.

### CODE REVIEW

**Comment by cgranade** [comment]
Thanks! I've also deprecated ``ClusteringResampler``, since that was an unmaintained experiment. It already was undocumented and not imported by default, so I think this is a fairly low-impact deprecation.

**Comment by whitewhim2718** [comment]
Yah that makes sense. I still would like to work on the clustering you
mentioned when you were here in Waterloo. It may have to wait until after I
finish writing my thesis though.

On Sep 22, 2016 9:48 PM, "Chris Granade" <notifications@github.com> wrote:

Thanks! I've also deprecated ClusteringResampler, since that was an
unmaintained experiment. It already was undocumented and not imported by
default, so I think this is a fairly low-impact deprecation.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/QInfer/python-qinfer/pull/96#issuecomment-249080000>,
or mute the thread

**Comment by cgranade** [comment]
Agreed, I'd very much like to work on it as well; in fact, that's part of my motivation for deprecating this feature. I don't think that the current design of ``ClusteringResampler`` is the right way to do that, even though the ideas are still interesting.

**Comment by cgranade** [comment]
I'm not sure why the CI builds are broken. Again. Investigating now.

**Comment by cgranade** [comment]
I think changing the backend for Matplotlib did it, there seems to be some sort of a conflict with the recent updates to Qt. Strangely, installing older versions didn't help, but this is more correct anyway, in that we shouldn't have our tests contingent on Qt at all.

**Comment by cgranade** [comment]
Welp, that was annoying. Merging now.

**Pull request merged**
