### PR TITLE
Added SumDistribution. Minor fix for perf_test.

### PR DESCRIPTION
**Pull request by ysanders**
I was intending to create a separate pull request for SumDistribution (added to distribution.py) and the fix for perf_test (added to perf_testing.py) but I'm still a bit of a newbie with git.

- I did a trivial test of SumDistribution, but it will need a code review.

- perf_test wasn't saving the estimate correctly, so I fixed the relevant line.

### CODE REVIEW

**Comment by cgranade** [comment]
Ah, thanks for catching that bug and for the new distribution. As a minor suggestion, perhaps ``SumDistribution`` should be called ``MixtureDistribution`` instead, as it's not a sum of random variables, but of their PDFs? Also, it might make sense for ``weights`` to be a keyword arg so that it can default to uniform if not specified? Thank you again for the PR!

**Comment by ysanders** [comment]
Makes sense. I also found some flaws in the current implementation, so I'll fix that sometime over the next couple of weeks — I'm writing up and will use that piece of code for one of my thesis plots.

**Comment by cgranade** [comment]
Bumping this as I'm interested in closing PRs going into 1.0. Thanks!

**Comment by ihincks** [comment]
I didn't catch this PR and independently wrote a MixtureDistribution class -- I can try to merge those ideas in here, in particular I use the np.rando multinomial distribution on the weights so that you don't end up sampling the same distribution with n=1 multiple times.

**Comment by cgranade** [comment]
This has now been superceded by #93, as that PR includes all changes from this PR. Thanks for the contribution!

**Pull request closed without merging**
