### PR TITLE
Remove docopt

### PR DESCRIPTION
**Pull request by cgranade**
This PR completely removes docopt from ``_lib`` since we're no longer using it at all.

### CODE REVIEW

**Comment by cgranade** [comment]
Since this passes all tests, I think that's a pretty good indication that there's not any dependencies on docopt that I missed. Should be ready to merge in once #121 is merged.

**Comment by ihincks** [comment]
Would you mind just triggering a travis rebuild to be safe? I usually just do `git commit --allow-empty -m ..", but apparently the travis website also has a refresh button for those with admin access.

**Comment by cgranade** [comment]
Sounds good, will do. I apologize about not exposing the "Restart build" option, there doesn't seem to be a way to delegate or share access to the Travis build controls. One workaround I've found that's a bit of a pain is to use your own fork of the repo so that you have direct control over Travis on that fork. Certainly not a great option, though, given that you really should just have access to build controls directly.

**Comment by cgranade** [comment]
Looks like the tests still pass under the fresh build, so I think that's a pretty good indication that we haven't missed anything.

**Pull request merged**
